name: flutter_app
description: "Flutter Web port of GlossipUerj."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.2
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  image: ^4.5.4
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
